name: Run Ultroid With UltroidCli On Github Actions
on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
    - dev
  workflow_dispatch:


env:
  api_id: 2835240
  api_hash: '662828e2071961e4977b5d1e1a90771e'
  session: '1BVtsOJgBu56xw9eWyg_BBmkWQEloDglLwzS1DmqlIvZsqss267_Fx3cg5vCSTVWJd_X7lcF2HL9wcj2Pol7RDB2T6uP0y-ogES9-L5HuNFyYF45dffp3lVA0bEWKxp8TjWGGQBTTzQRBQygX5BRid1xnIXk9ZVbW__5ZgPP5dkXOi4LtqjCZO_5KrreldvuL2IL-1-nhWgamznVzyBLLssi7GczUaS5qdWve3-Fc97E_iQbyzyWa2jETYoRSa6K2vHFSTh1RZTtoxuRh-jCP16drQgTnGryJ3oRz7qmucshQyS2iPffBhHqzbCiszfzHm_0IwqLehXrauheUl3glUPp-LkHXJ9M='
  redis_uri: 'redis-12201.c8.us-east-1-2.ec2.cloud.redislabs.com:12201'
  redis_password: 'YDyUq8DzwJvGpHpJZcUseuL9RH99o3ba'
  log_channel: -1001712580343
  bot_token: '2030098447:AAFHE-RHHJKuZ9J_RnW6GlsjB_m91qIWL6E'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cancel Duplicate Workflows
        uses: styfle/cancel-workflow-action@0.9.0
        with:
            all_but_latest: true
            access_token: ${{ github.token }}
      - name: Run With UltroidCli
        continue-on-error: true
        uses: ./
